In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib widget

In [2]:
df = pd.read_csv("/Users/zgl12/Modules/DES_Param_Analysis/run_publication_registry.csv")

baseline_val = df[df['run_name'] == 'baseline']["logZ"].values[0]

In [3]:
df

,run_name,timestamp,nlive,ndim,N_sne,dof,logZ,logZ_err,chi2,chi2_dof,...,tau_mean,tau_std,M1_mean,M1_std,xi_sSFR_mass_mean,xi_sSFR_mass_std,xi_sSFR_col_mean,xi_sSFR_col_std,omega_mean,omega_std
0,nuisance/noalphagamma,2026-08-27T00:52:22,1500,3,1820,1817,-988.155,0.055,2776.536,1.5281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,nuisance/noalphabeta,2026-08-27T01:09:26,1500,3,1820,1817,-2346.387,0.093,5473.981,3.0126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,nuisance/nobetagamma,2026-08-27T01:13:55,1500,3,1820,1817,-1980.134,0.096,4740.458,2.6089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,nuisance/noalpha,2026-08-27T01:23:08,2000,4,1820,1816,-980.372,0.066,2754.507,1.5168,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,nuisance/nogamma,2026-08-27T01:28:01,2000,4,1820,1816,-450.908,0.066,1694.916,0.9333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,ssfr/ssfr_sigmoid_F0ftau_hcol_quadratic_mass_s...,2026-09-02T01:17:06,5500,11,1820,1809,-444.940,0.055,1661.016,0.9182,...,1.35783,0.74927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,ssfr/ssfr_tanh_F0ftau_hcol_tanh_mass_sigmoid_M...,2026-09-02T01:44:21,5500,11,1820,1809,-441.059,0.048,1660.298,0.9178,...,1.45242,0.80808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,ssfr/ssfr_tanh_F0ftau_hcol_quadratic_mass_sigm...,2026-09-02T02:05:46,5500,11,1820,1809,-443.560,0.053,1660.917,0.9181,...,1.35252,0.75832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,ssfr/ssfr_sigmoid_F0ftau_hcol_asymm_mass_sigmo...,2026-09-02T03:16:15,6000,12,1820,1808,-444.207,0.051,1659.178,0.9177,...,1.40832,0.76075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,ssfr/ssfr_tanh_F0ftau_hcol_asymm_mass_sigmoid_...,2026-09-02T04:35:35,6000,12,1820,1808,-442.852,0.049,1658.941,0.9176,...,1.39026,0.77449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
def section_df(df, substring):
    temp_df = df[df['run_name'].str.contains(substring)]
    return temp_df[temp_df['logZ'] >= (baseline_val+1)]

In [5]:
# df.sort_values(by=["chi2_dof"], ascending=True).head(20)

In [6]:
# df.sort_values(by=["chi2"], ascending=True).head(20)

In [7]:
section_df(df, 'stretch/').sort_values(by=["logZ"], ascending=False).head(20)

Empty DataFrame
Columns: [run_name, timestamp, nlive, ndim, N_sne, dof, logZ, logZ_err, chi2, chi2_dof, logL_max, AIC, BIC, M_hat, cosmo_type, sn_colour_model, x1_correction_model, mass_model, host_colour_model, ssfr_model, z_evolve_model, zlo, zhi, x1_range, c_range, idsurvey, mass_cut, host_quality_cut, obs_z_type, active_params, prior_overrides, n_gh_nodes, host_colour_err, ssfr_err_max, host_var_penalty, beta_mean, Om0_mean, eta_mean, beta_std, Om0_std, eta_std, gamma_mean, gamma_std, alpha_mean, alpha_std, x1_tau_mean, x1_tau_std, Ode0_mean, Ode0_std, sn_tau_mean, sn_tau_std, b_mean, b_std, x1_0_mean, x1_0_std, c0_mean, c0_std, a_mean, a_std, g_mean, g_std, w_mean, w_std, C0_mean, zeta_mean, F0_mean, ftau_mean, C0_std, zeta_std, F0_std, ftau_std, k1_mean, k2_mean, k3_mean, k1_std, k2_std, k3_std, htau_mean, htau_std, M0_mean, M0_std, xi_mass_col_mean, xi_mass_col_std, beta_gamma_mean, beta_gamma_std, beta_alpha_mean, beta_alpha_std, gamma_alpha_mean, gamma_alpha_std, tau_mean, tau_std, M1_mean, M1_std, xi_sSFR_mass_mean, xi_sSFR_mass_std, xi_sSFR_col_mean, xi_sSFR_col_std, omega_mean, omega_std]
Index: []

[0 rows x 99 columns]

In [8]:
section_df(df, 'evolution/').sort_values(by=["logZ"], ascending=False).head(20)

Empty DataFrame
Columns: [run_name, timestamp, nlive, ndim, N_sne, dof, logZ, logZ_err, chi2, chi2_dof, logL_max, AIC, BIC, M_hat, cosmo_type, sn_colour_model, x1_correction_model, mass_model, host_colour_model, ssfr_model, z_evolve_model, zlo, zhi, x1_range, c_range, idsurvey, mass_cut, host_quality_cut, obs_z_type, active_params, prior_overrides, n_gh_nodes, host_colour_err, ssfr_err_max, host_var_penalty, beta_mean, Om0_mean, eta_mean, beta_std, Om0_std, eta_std, gamma_mean, gamma_std, alpha_mean, alpha_std, x1_tau_mean, x1_tau_std, Ode0_mean, Ode0_std, sn_tau_mean, sn_tau_std, b_mean, b_std, x1_0_mean, x1_0_std, c0_mean, c0_std, a_mean, a_std, g_mean, g_std, w_mean, w_std, C0_mean, zeta_mean, F0_mean, ftau_mean, C0_std, zeta_std, F0_std, ftau_std, k1_mean, k2_mean, k3_mean, k1_std, k2_std, k3_std, htau_mean, htau_std, M0_mean, M0_std, xi_mass_col_mean, xi_mass_col_std, beta_gamma_mean, beta_gamma_std, beta_alpha_mean, beta_alpha_std, gamma_alpha_mean, gamma_alpha_std, tau_mean, tau_std, M1_mean, M1_std, xi_sSFR_mass_mean, xi_sSFR_mass_std, xi_sSFR_col_mean, xi_sSFR_col_std, omega_mean, omega_std]
Index: []

[0 rows x 99 columns]

In [9]:
section_df(df, 'sncolour/').sort_values(by=["logZ"], ascending=False).head(20)

,run_name,timestamp,nlive,ndim,N_sne,dof,logZ,logZ_err,chi2,chi2_dof,...,tau_mean,tau_std,M1_mean,M1_std,xi_sSFR_mass_mean,xi_sSFR_mass_std,xi_sSFR_col_mean,xi_sSFR_col_std,omega_mean,omega_std
26,sncolour/sncolour_softbroken_sntau,2026-08-27T03:32:35,3000,6,1820,1814,-449.234,0.064,1682.132,0.9273,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,sncolour/sncolour_quadratic_c0,2026-08-27T03:44:33,3000,6,1820,1814,-450.291,0.067,1682.198,0.9273,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,sncolour/sncolour_stepbroken_sntau,2026-08-27T10:38:35,3000,6,1820,1814,-450.758,0.069,1681.671,0.9271,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,sncolour/sncolour_tanh_c0,2026-08-27T03:48:03,3000,6,1820,1814,-450.863,0.068,1682.251,0.9274,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,sncolour/sncolour_softbroken_c0sntau,2026-08-27T05:05:33,3500,7,1820,1813,-451.405,0.063,1682.138,0.9278,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,sncolour/sncolour_asymm_gauss_weight_c0sntau,2026-08-27T11:58:47,3500,7,1820,1813,-451.777,0.064,1682.289,0.9279,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
section_df(df, 'host_col/').sort_values(by=["logZ"], ascending=False).head(20)

,run_name,timestamp,nlive,ndim,N_sne,dof,logZ,logZ_err,chi2,chi2_dof,...,tau_mean,tau_std,M1_mean,M1_std,xi_sSFR_mass_mean,xi_sSFR_mass_std,xi_sSFR_col_mean,xi_sSFR_col_std,omega_mean,omega_std
95,host_col/ssfr_none_hcol_sigmoid_C0_mass_linear,2026-08-27T09:48:46,3000,6,1820,1814,-446.154,0.055,1683.966,0.9283,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,host_col/ssfr_none_hcol_sigmoid_C0_mass_double...,2026-08-27T10:01:37,3000,6,1820,1814,-446.357,0.055,1684.044,0.9284,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,host_col/ssfr_none_hcol_quadratic_C0_mass_linear,2026-08-27T10:27:06,3000,6,1820,1814,-446.642,0.061,1680.402,0.9264,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,host_col/ssfr_none_hcol_tanh_C0_mass_linear,2026-08-27T10:35:46,3000,6,1820,1814,-446.894,0.054,1682.349,0.9274,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,host_col/ssfr_none_hcol_tanh_C0_mass_double_step,2026-08-27T10:44:47,3000,6,1820,1814,-447.055,0.055,1682.427,0.9275,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,host_col/ssfr_none_hcol_quadratic_C0_mass_doub...,2026-08-27T10:37:10,3000,6,1820,1814,-447.427,0.062,1681.404,0.9269,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,host_col/ssfr_none_hcol_sigmoid_C0_mass_sigmoi...,2026-08-27T12:10:45,4000,8,1820,1812,-447.931,0.052,1683.256,0.9289,...,1.94603,1.04612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,host_col/ssfr_none_hcol_linear_mass_sigmoid_M0tau,2026-08-27T10:48:29,3500,7,1820,1813,-447.970,0.053,1684.969,0.9294,...,1.37397,0.91483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,host_col/ssfr_none_hcol_asymm_C0htau_mass_linear,2026-08-27T11:14:32,3500,7,1820,1813,-447.989,0.052,1682.132,0.9278,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,host_col/ssfr_none_hcol_asymm_C0htau_mass_doub...,2026-08-27T11:19:02,3500,7,1820,1813,-448.138,0.053,1682.143,0.9278,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,host_col/ssfr_none_hcol_linear_mass_tanh_M0tau,2026-08-27T11:23:15,3500,7,1820,1813,-448.424,0.054,1684.923,0.9294,...,1.19647,0.98270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,host_col/ssfr_none_hcol_linear_mass_linear,2026-08-27T08:56:04,2500,5,1820,1815,-448.458,0.063,1687.103,0.9295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,host_col/ssfr_none_hcol_broken_C0_mass_linear,2026-08-27T10:00:36,3000,6,1820,1814,-448.463,0.059,1683.818,0.9282,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,host_col/ssfr_none_hcol_sigmoid_C0_mass_linear...,2026-08-27T11:17:40,3500,7,1820,1813,-448.513,0.057,1683.698,0.9287,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,host_col/ssfr_none_hcol_linear_mass_tanh_M0,2026-08-27T10:17:08,3000,6,1820,1814,-448.532,0.056,1687.082,0.9300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,host_col/ssfr_none_hcol_tanh_C0_mass_sigmoid_t...,2026-08-27T13:18:00,4000,8,1820,1812,-448.631,0.051,1681.914,0.9282,...,1.92496,1.04249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,host_col/ssfr_none_hcol_linear_mass_double_step,2026-08-27T09:07:50,2500,5,1820,1815,-448.631,0.064,1687.054,0.9295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,host_col/ssfr_none_hcol_broken_C0_mass_double_...,2026-08-27T10:14:23,3000,6,1820,1814,-448.650,0.060,1683.828,0.9282,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,host_col/ssfr_none_hcol_asymm_C0htau_mass_sigm...,2026-08-27T13:56:29,4500,9,1820,1811,-449.087,0.049,1681.679,0.9286,...,2.05907,1.01278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,host_col/ssfr_none_hcol_linear_mass_double_ste...,2026-08-27T11:27:21,3500,7,1820,1813,-449.132,0.058,1680.350,0.9268,...,NaN,NaN,10.80752,0.28249,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
section_df(df, 'mass/').sort_values(by=["logZ"], ascending=False).head(20)

,run_name,timestamp,nlive,ndim,N_sne,dof,logZ,logZ_err,chi2,chi2_dof,...,tau_mean,tau_std,M1_mean,M1_std,xi_sSFR_mass_mean,xi_sSFR_mass_std,xi_sSFR_col_mean,xi_sSFR_col_std,omega_mean,omega_std
181,mass/mass_sigmoid_M0tau,2026-08-27T20:19:23,3000,6,1820,1814,-446.952,0.048,1690.310,0.9318,...,1.01849,0.44706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,mass/mass_linear,2026-08-27T15:33:44,2000,4,1820,1816,-447.335,0.056,1693.918,0.9328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,mass/mass_tanh_M0tau,2026-08-27T21:04:54,3000,6,1820,1814,-447.402,0.049,1690.316,0.9318,...,1.75139,0.84872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,mass/mass_double_step,2026-08-27T15:32:37,2000,4,1820,1816,-448.085,0.056,1695.374,0.9336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,mass/mass_double_step_M0M1,2026-08-27T21:50:15,3000,6,1820,1814,-448.973,0.055,1686.799,0.9299,...,NaN,NaN,10.69713,0.12113,NaN,NaN,NaN,NaN,NaN,NaN
175,mass/mass_sigmoid_M0,2026-08-27T19:09:41,2500,5,1820,1815,-449.995,0.053,1696.399,0.9347,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,mass/mass_sigmoid,2026-08-27T15:37:05,2000,4,1820,1816,-450.623,0.056,1699.982,0.9361,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,mass/mass_spline_k1k2k3,2026-08-27T21:39:09,3500,7,1820,1813,-450.736,0.047,1696.753,0.9359,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,mass/mass_tanh_M0,2026-08-27T19:13:25,2500,5,1820,1815,-451.235,0.050,1699.660,0.9365,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
section_df(df, 'interaction/').sort_values(by=["logZ"], ascending=False).head(20)

,run_name,timestamp,nlive,ndim,N_sne,dof,logZ,logZ_err,chi2,chi2_dof,...,tau_mean,tau_std,M1_mean,M1_std,xi_sSFR_mass_mean,xi_sSFR_mass_std,xi_sSFR_col_mean,xi_sSFR_col_std,omega_mean,omega_std
114,interaction/interaction_gammaalpha,2026-08-27T10:31:14,3000,6,1820,1814,-450.762,0.068,1682.71,0.9276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
section_df(df, 'ssfr/').sort_values(by=["logZ"], ascending=False).head(20)

,run_name,timestamp,nlive,ndim,N_sne,dof,logZ,logZ_err,chi2,chi2_dof,...,tau_mean,tau_std,M1_mean,M1_std,xi_sSFR_mass_mean,xi_sSFR_mass_std,xi_sSFR_col_mean,xi_sSFR_col_std,omega_mean,omega_std
412,ssfr/ssfr_tanh_hcol_none_mass_linear,2026-09-01T13:16:48,2500,5,1820,1815,-439.837,0.063,1670.093,0.9202,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,ssfr/ssfr_tanh_hcol_tanh_mass_linear,2026-09-01T16:53:04,3500,7,1820,1813,-439.978,0.057,1664.669,0.9182,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
452,ssfr/ssfr_tanh_F0ftau_hcol_none_mass_sigmoid_M...,2026-09-01T18:18:35,4500,9,1820,1811,-440.630,0.050,1667.063,0.9205,...,1.58201,0.91014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,ssfr/ssfr_tanh_hcol_sigmoid_mass_linear,2026-09-01T16:05:44,3500,7,1820,1813,-440.674,0.057,1666.569,0.9192,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,ssfr/ssfr_tanh_F0ftau_hcol_none_mass_linear,2026-08-29T17:14:46,3500,7,1820,1813,-440.884,0.057,1667.267,0.9196,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,ssfr/ssfr_tanh_F0ftau_hcol_tanh_mass_linear,2026-08-29T22:59:28,4500,9,1820,1811,-440.896,0.054,1660.827,0.9171,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,ssfr/ssfr_tanh_F0ftau_hcol_tanh_mass_sigmoid_M...,2026-09-02T01:44:21,5500,11,1820,1809,-441.059,0.048,1660.298,0.9178,...,1.45242,0.80808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,ssfr/ssfr_tanh_F0ftau_hcol_sigmoid_mass_linear,2026-08-29T21:19:16,4500,9,1820,1811,-441.624,0.054,1663.038,0.9183,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,ssfr/ssfr_tanh_hcol_asymm_mass_linear,2026-09-01T18:34:47,4000,8,1820,1812,-441.636,0.057,1662.556,0.9175,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
444,ssfr/ssfr_step_F0_hcol_none_mass_sigmoid_M0tau,2026-09-01T17:08:17,4000,8,1820,1812,-441.748,0.056,1665.877,0.9194,...,1.58502,0.93326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,ssfr/ssfr_tanh_F0ftau_hcol_sigmoid_mass_sigmoi...,2026-09-01T23:02:48,5500,11,1820,1809,-441.850,0.049,1662.617,0.9191,...,1.44343,0.77800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,ssfr/ssfr_step_F0_hcol_tanh_mass_linear,2026-08-29T04:18:45,4000,8,1820,1812,-441.885,0.060,1659.512,0.9158,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,ssfr/ssfr_step_F0_hcol_none_mass_linear,2026-08-27T22:38:07,3000,6,1820,1814,-441.937,0.065,1665.993,0.9184,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,ssfr/ssfr_step_F0_hcol_tanh_mass_sigmoid_M0tau,2026-09-01T22:46:49,5000,10,1820,1810,-441.937,0.053,1658.810,0.9165,...,1.41442,0.81767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,ssfr/ssfr_sigmoid_F0ftau_hcol_tanh_mass_linear,2026-08-29T22:31:09,4500,9,1820,1811,-442.058,0.056,1660.755,0.9170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,ssfr/ssfr_sigmoid_F0ftau_hcol_none_mass_sigmoi...,2026-09-01T18:06:55,4500,9,1820,1811,-442.196,0.052,1667.226,0.9206,...,1.57787,0.90594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
415,ssfr/ssfr_tanh_hcol_none_mass_sigmoid,2026-09-01T13:27:47,2500,5,1820,1815,-442.302,0.063,1674.477,0.9226,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,ssfr/ssfr_sigmoid_F0ftau_hcol_tanh_mass_sigmoi...,2026-09-02T00:51:00,5500,11,1820,1809,-442.357,0.050,1660.129,0.9177,...,1.43160,0.78499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,ssfr/ssfr_sigmoid_F0ftau_hcol_none_mass_linear,2026-08-29T16:22:30,3500,7,1820,1813,-442.433,0.059,1667.570,0.9198,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,ssfr/ssfr_step_F0_hcol_sigmoid_mass_linear,2026-08-28T03:20:08,4000,8,1820,1812,-442.590,0.060,1661.774,0.9171,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN